"""Create initial database schema

Revision ID: d953c36411e0
Revises:
Create Date: 2025-10-02 17:40:06.690656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd953c36411e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True, comment="e.g., 'manual', 'priority', 'idle'"),
    sa.Column('frequency_hz', sa.Integer(), nullable=True),
    sa.Column('bandwidth_hz', sa.Integer(), nullable=True),
    sa.Column('gains', sa.JSON(), nullable=True),
    sa.Column('timestamp_start', sa.DateTime(), nullable=True),
    sa.Column('timestamp_end', sa.DateTime(), nullable=True),
    sa.Column('rssi_avg_dbm', sa.Float(), nullable=True),
    sa.Column('file_paths', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captures_id'), 'captures', ['id'], unique=False)
    op.create_index(op.f('ix_captures_mode'), 'captures', ['mode'], unique=False)
    op.create_index(op.f('ix_captures_uuid'), 'captures', ['uuid'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('noaa_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=False),
    sa.Column('satellite_name', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('max_elevation', sa.Float(), nullable=True),
    sa.Column('azimuth', sa.Float(), nullable=True),
    sa.Column('timestamp_decoded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capture_id'),
    sa.UniqueConstraint('image_path')
    )
    op.create_index(op.f('ix_noaa_images_id'), 'noaa_images', ['id'], unique=False)
    op.create_index(op.f('ix_noaa_images_satellite_name'), 'noaa_images', ['satellite_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_noaa_images_satellite_name'), table_name='noaa_images')
    op.drop_index(op.f('ix_noaa_images_id'), table_name='noaa_images')
    op.drop_table('noaa_images')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_captures_uuid'), table_name='captures')
    op.drop_index(op.f('ix_captures_mode'), table_name='captures')
    op.drop_index(op.f('ix_captures_id'), table_name='captures')
    op.drop_table('captures')
    # ### end Alembic commands ###
